quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/flow
quarkus.datasource.username=flow
quarkus.datasource.password=flow
quarkus.hibernate-orm.database.generation=update

#quarkus.log.level=INFO
#quarkus.log.min-level=TRACE

#quarkus.hibernate-orm.log.sql=true
#quarkus.hibernate-orm.log.format-sql=true
#quarkus.hibernate-orm.log.highlight-sql=true
#quarkus.hibernate-orm.log.bind-parameters=true

#quarkus.log.category."org.hibernate.SQL".level=DEBUG
